### ISSUE TITLE
Integrate synced changes from nextjs template fork

### ISSUE THREAD

**Issue by Kasshern** [MeshDevs/chain-connector-ui#4]
## Title
Integrate synced changes from nextjs template fork

## Type

Technical - Does not translate to user functionality, but are important for the system to operate effectively ie. System performance, security, scalability, usability, maintainability, etc. "As a system, I need to handle 100,000 concurrent users so that our service remains available during peak usage times". 

## Description
"As a developer I want to take advantage of the templates upgrades or bug fixes"

## Acceptance Criteria

- [x] changes of the forked template repo are pulled into chain-connector-ui
- [x] conflicts resolved and rebase considered
- [x] changes have not affected gui frontend

## Tasks

- [x] ensure changes of the forked template repo are pulled into chain-connector-ui
- [x] ensure resolve conflicts and consider rebase
- [x] Test that changes have not affected gui frontend
